Completed css-layout-classes exercise. - Justin Son
justintaeson/c0122-code-solutions pull request #16
Opened 2022-01-27 21:22 UTC by justintaeson

https://user-images.githubusercontent.com/97268025/151445739-60815994-5d98-47dd-a4c5-393766672bc1.mov

2022-01-27 22:42 UTC, codingcodymiller requested changes

2022-01-27 22:42 UTC, codingcodymiller commented on css-layout-classes/styles.css
> +}
You should only set `width` or `flex-basis` on column classes, not both

2022-01-27 22:45 UTC, justintaeson commented
![css-layout-classes_1 27 22 V2](https://user-images.githubusercontent.com/97268025/151455857-6f4252e0-f79c-4cc3-9d8c-2afd0646c7e9.png)

2022-01-28 01:07 UTC, codingcodymiller approved these changes

2022-01-28 19:24 UTC, merged