Completed css-two-column-layout exercise. - Justin Son
justintaeson/c0122-code-solutions pull request #24
Opened 2022-02-01 02:00 UTC by justintaeson

![css-two-column-layout_1 31 22](https://user-images.githubusercontent.com/97268025/151902469-947e978c-ec31-4c37-8f33-9eea1acb9f39.png)

2022-02-01 23:06 UTC, codingcodymiller requested changes
Hey Justin, your output is missing the button, please revise

2022-02-02 04:46 UTC, justintaeson commented
![css-two-column-layout_V2_2 1 22](https://user-images.githubusercontent.com/97268025/152094608-f300e583-ae82-4d4c-ae00-abd5c294bf22.png)

2022-02-04 18:27 UTC, codingcodymiller requested changes

2022-02-04 18:27 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.column {
`column` what? Remember that column classes should be named after their size.

2022-02-07 07:19 UTC, justintaeson commented
![css-two-column-layout_v2_2 6 22](https://user-images.githubusercontent.com/97268025/152742388-25e19f76-d947-4a0b-94c5-b4d9588200a7.png)

2022-02-07 18:02 UTC, codingcodymiller approved these changes

2022-02-07 18:43 UTC, merged