Completed css-canvas-medical exercise. - Justin Son
justintaeson/c0122-code-solutions pull request #29
Opened 2022-02-02 18:38 UTC by justintaeson

![css-canvas-medical_B_2 2 22](https://user-images.githubusercontent.com/97268025/152216743-c2354ab2-1c51-459d-aa8b-e14bd9206655.png)
![css-canvas-medical_A_2 2 22](https://user-images.githubusercontent.com/97268025/152216749-59c2bdb9-9d53-48aa-9841-471c3cf2223e.png)

2022-02-04 18:35 UTC, codingcodymiller requested changes

2022-02-04 18:35 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="column">
`column` what? Did you only need one size of `column` for your entire layout? How wide is the `column` meant to be?

2022-02-04 18:35 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +    <br>
No `br` elements, if you need additional space, you should use `margin` or `padding`

2022-02-04 18:35 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
`column` classes are meant to have either `flex-basis` or `width`, and that's it. This is not a proper layout class setup, I suggest reviewing `css-layout-classes` for a refresher.

2022-02-04 18:35 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
None of these elements should require using `absolute` positioning, you should use proper layout classes.

2022-02-04 18:35 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
This shouldn't be `absolute` either 🤢

2022-05-02 22:12 UTC, thebearingedge approved these changes

2022-05-03 21:01 UTC, merged