Completed css-four-column-layout challenge. - Justin Son
justintaeson/c0122-code-solutions pull request #32
Opened 2022-02-03 16:37 UTC by justintaeson

<img width="876" alt="css-four-column-layout_2 3 22" src="https://user-images.githubusercontent.com/97268025/152386633-fc764fc1-0df1-4fbd-a6f9-293ee062bece.png">

2022-02-04 19:43 UTC, codingcodymiller requested changes

2022-02-04 19:43 UTC, codingcodymiller commented on css-four-column-layout/index.html
> +  </div>
I can see why you would do this from the perspective of layout classes, but by putting the images, icons, and text in separate rows, your HTML looks like this content is not related to one another. You should have one row with four columns, and each column contains the phone image, icon, and text all together.

2022-02-07 07:15 UTC, justintaeson commented
![css-four-column-layout_v2_2 6 22](https://user-images.githubusercontent.com/97268025/152741886-5012620a-bb27-4380-9011-0381f2eabb28.png)

2022-02-07 18:06 UTC, codingcodymiller approved these changes

2022-02-07 18:43 UTC, merged