Completed javascript-loops-practice exercise. - Justin Son
justintaeson/c0122-code-solutions pull request #33
Opened 2022-02-04 00:43 UTC by justintaeson

![javascript-loops-practice_2 3 22](https://user-images.githubusercontent.com/97268025/152453315-48a4aeb4-1a54-4481-a352-bdbdf95e3e97.png)

2022-02-04 20:48 UTC, codingcodymiller requested changes

2022-02-04 20:48 UTC, codingcodymiller commented on javascript-loops-practice/filter-out-strings.js
> +    if (typeof values[i] === 'number') {
This function isn't supposed to collect all numbers, it's supposed to collect all values that are not strings.

2022-02-04 20:48 UTC, codingcodymiller commented on javascript-loops-practice/get-indexes.js
> +    index = array.indexOf(array[i]);
This is unnecessary, you can just use `i`

2022-02-04 23:23 UTC, justintaeson commented
![javascript-loops-practice_v2_2 4 22](https://user-images.githubusercontent.com/97268025/152616105-40d9540d-38d6-4c1b-9624-a9cfcb0c3d57.png)

2022-02-05 00:31 UTC, codingcodymiller approved these changes

2022-02-06 20:03 UTC, merged