Completed object-manipulation-1 exercise. - Justin Son
justintaeson/c0122-code-solutions pull request #37
Opened 2022-02-07 04:54 UTC by justintaeson

<img width="706" alt="object-manipulation-1_2 6 22" src="https://user-images.githubusercontent.com/97268025/152726576-f87c9df1-e5a3-4f11-b7bd-2fe97762dc8a.png">

2022-02-07 20:46 UTC, codingcodymiller requested changes

2022-02-07 20:46 UTC, codingcodymiller commented on object-manipulation-1/src/to-object.js
> +    if (i === 0 || i % 2 === 0) {
Why is this necessary? I don't think you'll need a loop here, you already know the indexes for the two values you need: `0` and `1`

2022-02-08 01:33 UTC, justintaeson commented
![object-manipulation-1_v2_2 7 22](https://user-images.githubusercontent.com/97268025/152901057-11ed5cdb-4ffd-43cd-b2ef-9c56e9e6544c.png)

2022-02-09 16:02 UTC, thebearingedge approved these changes

2022-02-09 18:40 UTC, merged