Completed css-eccomerce-page exercise. - Justin Son
justintaeson/c0122-code-solutions pull request #38
Opened 2022-02-07 07:43 UTC by justintaeson

![css-ecommerce-page_2 6 22](https://user-images.githubusercontent.com/97268025/152745640-517d221d-615f-4b65-9cd9-1f1850defc52.png)

2022-02-07 18:11 UTC, codingcodymiller requested changes

2022-02-07 18:11 UTC, codingcodymiller commented on css-ecommerce-page/index.html
> +  </div>
You should have the images and the text for the images in their own `column` class element together, not in separate `row` elements. 

Also, please give your `column` class a name that describes its size.

2022-02-08 01:43 UTC, justintaeson commented
![css-ecommerce-page_v2_2 7 22](https://user-images.githubusercontent.com/97268025/152902025-7ed5b2dc-305b-4ab4-86d3-f5404350d0bf.png)

2022-02-09 15:47 UTC, thebearingedge approved these changes

2022-02-09 18:40 UTC, merged