Completed dom-manipulation exercise. - Justin Son
justintaeson/c0122-code-solutions pull request #41
Opened 2022-02-08 01:14 UTC by justintaeson

https://user-images.githubusercontent.com/97268025/152899211-8a6bc0de-a523-440f-ae93-1585d51658ed.mov

2022-02-08 19:10 UTC, codingcodymiller requested changes

2022-02-08 19:10 UTC, codingcodymiller commented on dom-manipulation/main.js
> +  if (numberOfClicks >= 16) {
If you use `else if` statements, you could greatly simplify this.

2022-02-08 20:47 UTC, justintaeson commented
https://user-images.githubusercontent.com/97268025/153072904-4d84db99-55c1-4033-881c-0bb1fc5184e2.mov

2022-02-09 16:07 UTC, thebearingedge approved these changes

2022-02-09 18:40 UTC, merged