Completed node-notes-cli challenge. - Justin Son
justintaeson/c0122-code-solutions pull request #80
Opened 2022-03-17 22:38 UTC by justintaeson

https://user-images.githubusercontent.com/97268025/158905715-3e9f5772-056a-4320-8cfa-c95a31d00cdf.mp4

2022-03-17 22:46 UTC, thebearingedge requested changes

2022-03-17 22:46 UTC, thebearingedge commented on node-notes-cli/app.js
> +  data.nextId = Object.keys(data.notes).length + 1;
This doesn't work if you delete some of your notes. Just increment the nextId property.

```js
data.nextId++;
```

2022-03-17 22:46 UTC, thebearingedge commented on node-notes-cli/app.js
> +  data.nextId = Object.keys(data.notes).length + 1;
The `data.nextId` should only be incremented when a new note is added.

2022-03-17 23:02 UTC, justintaeson commented
<img width="832" alt="Screen Shot 2022-03-17 at 4 00 19 PM" src="https://user-images.githubusercontent.com/97268025/158907956-b72567f7-42e1-41d0-a197-0499aa943db0.png">

2022-03-18 00:24 UTC, thebearingedge approved these changes

2022-03-18 00:54 UTC, merged