Completed express-get-json exercise. - Justin Son
justintaeson/c0122-code-solutions pull request #85
Opened 2022-03-19 18:51 UTC by justintaeson

https://user-images.githubusercontent.com/97268025/159134598-6d2e7e1d-6ca1-4615-8ad0-9e2bfdb7af07.mov

2022-03-21 15:26 UTC, thebearingedge requested changes

2022-03-21 15:26 UTC, thebearingedge commented on express-get-json/index.js
> +});
The client should receive an array instead of an object.

2022-03-22 05:14 UTC, justintaeson commented
<img width="1429" alt="Screen Shot 2022-03-21 at 10 09 36 PM" src="https://user-images.githubusercontent.com/97268025/159412638-65d0e895-86f8-4ad6-a85f-801eed6e5012.png">

2022-03-22 15:06 UTC, thebearingedge approved these changes

2022-03-22 17:16 UTC, merged